version: '3.9'
services:

    py_app:
        container_name: py_app
        build: ./app
        depends_on:
            -   redis
        stdin_open: true
        tty: true

    py_worker:
        container_name: py_worker
        build: ./worker
        depends_on:
            -   redis
        stdin_open: true
        tty: true

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]